import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Icon } from "@/components/Icon";
import { JsonLd } from "@/components/JsonLd";
import { PageHero } from "@/components/PageHero";
import { SITE_URL, specialties } from "@/data/site";

export function generateStaticParams(){return specialties.map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const item=specialties.find(s=>s.slug===slug);if(!item)return{};return{title:`${item.title} consultants`,description:item.description,alternates:{canonical:`/specialties/${slug}`},openGraph:{title:`${item.title} consultations`,description:item.description,url:`/specialties/${slug}`}}}
export default async function SpecialtyPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const item=specialties.find(s=>s.slug===slug);if(!item)notFound();return <><JsonLd data={{"@context":"https://schema.org","@type":"MedicalWebPage",name:`${item.title} consultations`,description:item.description,url:`${SITE_URL}/specialties/${item.slug}`,about:{"@type":"MedicalSpecialty",name:item.title}}}/><PageHero eyebrow="Medical specialty" title={`${item.title} consultations`} description={item.description}/><section className="content-section"><div className="container content-grid"><article className="prose"><h2>Find the appropriate care path</h2><p>This specialty page is prepared to receive verified consultant profiles, Arabic and English classification data, consultation durations, fees and date-specific slot states from the future public API.</p><h3>Before you book</h3><ul><li>Review each consultant&apos;s verified profile and classification.</li><li>Choose a consultation duration that is enabled for that consultant.</li><li>Compare available and already-booked times for the selected date.</li><li>Confirm the patient and review the complete payment summary.</li></ul><div className="notice">For urgent or emergency symptoms, contact the appropriate local emergency service rather than waiting for an online appointment.</div></article><aside className="info-panel"><span className="eyebrow">Prepared for live data</span><h3>{item.title}</h3><ul><li><Icon name="check"/> English and Arabic profiles</li><li><Icon name="check"/> Duration-aware availability</li><li><Icon name="check"/> Transparent appointment summaries</li></ul><Link href={`/consultants?specialty=${item.slug}`} className="button button-primary">View consultants <Icon name="arrow" size={18}/></Link></aside></div></section></>}
